### ISSUE TITLE
`Realm` in `wally.toml` is set to `"server"`

### ISSUE THREAD

**Issue by ghost** [ddavness/roblox-http-queue#1]
Currently in the [wally.toml](https://github.com/ddavness/roblox-http-queue/blob/master/wally.toml) file, `realm` is set to `"server"`, which means http queue can only be installed as a server dependency, which is a problem since I also want to use it on the client. `Realm` should be set to `"shared"` instead.

**Comment by ddavness** [comment]
What would be the use case for using the library on the client? It's not like it will work there. The library relies on `HttpService` and it only works on the server.

**Comment by ghost** [comment]
Ah yes, thanks for reminding me about that, totally forgot about that.
